name: daily task

on:
  schedule:
    - cron: '32 13 * * *'
  workflow_dispatch:

jobs:
  
  set-env:
    runs-on: ubuntu-latest
    outputs:
      ENV_NAME: ${{ steps.set-env-step.outputs.ENV_NAME }}
    steps:
      - name: Determine environment
        id: set-env-step
        run: |
          # Check if running on the default branch
          if [[ "${{ github.ref }}" == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            if [[ "${{ github.event_name }}" == "schedule" ]]; then
              ENV_NAME="production"  # For schedule trigger on default branch
            else
              ENV_NAME="staging"  # For manual trigger on default branch
            fi
          else
            ENV_NAME="development"
          fi
          
          # Set the environment variable
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_OUTPUT




  daily-task-for-production:
    if: github.event_name == 'schedule' & github.ref == format('refs/heads/{0}', github.event.repository.default_branch) # check if on schedule and on default_branch
    runs-on: ubuntu-latest
    steps:
      - name: Check if running on the default branch
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: echo "This is the default branch $DEFAULT_BRANCH"

  daily-task-for-staging:
    if: github.event_name == 'schedule' & github.ref =~ format('refs/heads/{0}', github.event.repository.default_branch) # check if on schedule and NOT on default_branch
    runs-on: ubuntu-latest

  environment-selection:
    runs-on: ubuntu-latest
    steps:
      - name: get default branch name
        run: echo "DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV

      - name: Check if running on the default branch
        if: github.ref == format('refs/heads/{0}', env.DEFAULT_BRANCH)
        run: echo "This is the default branch $DEFAULT_BRANCH"

  check-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger source
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Triggered manually!"
          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "Triggered by schedule!"
          else
            echo "Triggered by some other event: ${{ github.event_name }}"
          fi


        
