name: daily task

on:
  schedule:
    - cron: '32 13 * * *'
  workflow_dispatch:

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      ENV_NAME: ${{ steps.set-env-step.outputs.ENV_NAME }}  # Referencing the output from the step
    steps:
      - name: Determine environment
        id: set-env-step  # Make sure to reference this id when setting the output
        run: |
          # Check if running on the default branch
          if [[ "${{ github.ref }}" == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            if [[ "${{ github.event_name }}" == "schedule" ]]; then
              ENV_NAME="production"  # For schedule trigger on default branch
            else
              ENV_NAME="staging"  # For manual trigger on default branch
            fi
          else
            ENV_NAME="development"
          fi
          
          # Set the environment variable as step output
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_OUTPUT
          
  use-env:
    runs-on: ubuntu-latest
    needs: set-env  # Ensuring this job runs after set-env
    environment: ${{ needs.set-env.outputs.ENV_NAME }}  # Dynamic assignment to the 'name' of the environment
    steps:
      - name: Access ENV_NAME output from the set-env job
        run: |
          echo "The environment is: ${{ github.environment }}"
